=== ubsicap/versification_json/versification_as_json.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://burrito.bible/schema/versification_as_json.schema.json",
    "$$target": "canon_constraints.schema.json",
    "title": "Canon Constraints",
    "type": "object",
    "properties": {
        "basedOn": {},
        "verification": {},
        "maxVerses": {},
        "excludedVerses": {
            "type": "array"
        },
        "mappedVerses": {},
        "mergedVerses": {},
        "partialVerses": {
            "type": "object",
            "propertyNames": {
                "const": "banana"
            }
        },
        "additionalProperties": false
    },
    "required": [
        "maxVerses"
    ],
    "additionalProperties": false
}

=== ubsicap/versification_json/examples/one_versification.json
{
    "partialVerses": {
      "SIR 36:13": [
        "a"
      ],
      "SIR 36:16": [
        "b"
      ]
    },
    "excludedVerses": [
      "ISA 41:6",
      "ISA 41:7",
      "ACT 24:7",
      "ACT 28:29",
      "ROM 16:24",
      "TOB 5:23",
      "TOB 6:19",
      "TOB 10:14",
      "TOB 11:19",
      "ESG 4:6",
      "ESG 9:5",
      "ESG 9:32",
      "SIR 36:14",
      "SIR 36:15",
      "SIR 36:16",
      "SIR 41:23",
      "SIR 41:24",
      "SIR 41:25",
      "SIR 41:26",
      "SIR 41:27",
      "DAG 3:1",
      "DAG 3:2",
      "DAG 3:3",
      "DAG 3:4",
      "DAG 3:5",
      "DAG 3:6",
      "DAG 3:7",
      "DAG 3:8",
      "DAG 3:9",
      "DAG 3:10",
      "DAG 3:11",
      "DAG 3:12",
      "DAG 3:13",
      "DAG 3:14",
      "DAG 3:15",
      "DAG 3:16",
      "DAG 3:17",
      "DAG 3:18",
      "DAG 3:19",
      "DAG 3:20",
      "DAG 3:21",
      "DAG 3:22",
      "DAG 3:23",
      "4MA 10:4",
      "4MA 11:7",
      "4MA 11:8",
      "1ES 2:26",
      "1ES 3:24",
      "1ES 5:71"
    ],
    "maxVerses": {
      "JOS": [
        "18",
        "24",
        "17",
        "24",
        "15",
        "27",
        "26",
        "35",
        "27",
        "43",
        "23",
        "24",
        "33",
        "15",
        "63",
        "10",
        "18",
        "28",
        "51",
        "9",
        "45",
        "34",
        "16",
        "33"
      ],
      "BLT": [
        "42"
      ],
      "JON": [
        "16",
        "11",
        "10",
        "11"
      ],
      "JSA": [
        "18",
        "24",
        "17",
        "24",
        "15",
        "27",
        "26",
        "35",
        "27",
        "43",
        "23",
        "24",
        "33",
        "15",
        "63",
        "10",
        "18",
        "28",
        "51",
        "9",
        "45",
        "34",
        "16",
        "33"
      ],
      "NEH": [
        "11",
        "20",
        "38",
        "17",
        "19",
        "19",
        "72",
        "18",
        "37",
        "40",
        "36",
        "47",
        "31"
      ],
      "TIT": [
        "16",
        "15",
        "15"
      ],
      "REV": [
        "20",
        "29",
        "22",
        "11",
        "14",
        "17",
        "17",
        "13",
        "21",
        "11",
        "19",
        "18",
        "18",
        "20",
        "8",
        "21",
        "18",
        "24",
        "21",
        "15",
        "27",
        "21"
      ],
      "PHM": [
        "25"
      ],
      "4MA": [
        "35",
        "24",
        "21",
        "26",
        "38",
        "35",
        "23",
        "29",
        "32",
        "21",
        "27",
        "19",
        "27",
        "20",
        "32",
        "25",
        "24",
        "24"
      ],
      "LJE": [
        "72"
      ],
      "ISA": [
        "31",
        "22",
        "26",
        "6",
        "30",
        "13",
        "25",
        "23",
        "20",
        "34",
        "16",
        "6",
        "22",
        "32",
        "9",
        "14",
        "14",
        "7",
        "25",
        "6",
        "17",
        "25",
        "18",
        "23",
        "12",
        "21",
        "13",
        "29",
        "24",
        "33",
        "9",
        "20",
        "24",
        "17",
        "10",
        "22",
        "38",
        "22",
        "8",
        "31",
        "29",
        "25",
        "28",
        "28",
        "25",
        "13",
        "15",
        "22",
        "26",
        "11",
        "23",
        "15",
        "12",
        "17",
        "13",
        "12",
        "21",
        "14",
        "21",
        "22",
        "11",
        "12",
        "19",
        "11",
        "25",
        "24"
      ],
      "HAG": [
        "15",
        "23"
      ],
      "ZEC": [
        "17",
        "17",
        "10",
        "14",
        "11",
        "15",
        "14",
        "23",
        "17",
        "12",
        "17",
        "14",
        "9",
        "21"
      ],
      "1SA": [
        "28",
        "36",
        "21",
        "22",
        "12",
        "21",
        "17",
        "22",
        "27",
        "27",
        "15",
        "25",
        "23",
        "52",
        "35",
        "23",
        "58",
        "30",
        "24",
        "42",
        "16",
        "23",
        "28",
        "23",
        "44",
        "25",
        "12",
        "25",
        "11",
        "31",
        "13"
      ],
      "EZK": [
        "28",
        "10",
        "27",
        "17",
        "17",
        "14",
        "27",
        "18",
        "11",
        "22",
        "25",
        "28",
        "23",
        "23",
        "8",
        "63",
        "24",
        "32",
        "14",
        "44",
        "37",
        "31",
        "49",
        "27",
        "17",
        "21",
        "36",
        "26",
        "21",
        "26",
        "18",
        "32",
        "33",
        "31",
        "15",
        "38",
        "28",
        "23",
        "29",
        "49",
        "26",
        "20",
        "27",
        "31",
        "25",
        "24",
        "23",
        "35"
      ],
      "DAN": [
        "21",
        "49",
        "33",
        "34",
        "30",
        "29",
        "28",
        "27",
        "27",
        "21",
        "45",
        "13"
      ],
      "EZA": [
        "36",
        "52",
        "56",
        "59",
        "139",
        "63",
        "47",
        "60",
        "46",
        "51",
        "58",
        "48"
      ],
      "MAT": [
        "25",
        "23",
        "17",
        "25",
        "48",
        "34",
        "29",
        "34",
        "38",
        "42",
        "30",
        "50",
        "58",
        "36",
        "39",
        "28",
        "27",
        "35",
        "30",
        "34",
        "46",
        "46",
        "39",
        "51",
        "46",
        "75",
        "66",
        "20"
      ],
      "TBS": [
        "22",
        "14",
        "17",
        "21",
        "23",
        "19",
        "17",
        "21",
        "6",
        "14",
        "19",
        "22",
        "18",
        "15"
      ],
      "ROM": [
        "32",
        "29",
        "31",
        "25",
        "21",
        "23",
        "25",
        "39",
        "33",
        "21",
        "36",
        "21",
        "14",
        "23",
        "33",
        "27"
      ],
      "JDG": [
        "36",
        "23",
        "31",
        "24",
        "31",
        "40",
        "25",
        "35",
        "57",
        "18",
        "40",
        "15",
        "25",
        "20",
        "20",
        "31",
        "13",
        "31",
        "30",
        "48",
        "25"
      ],
      "SUS": [
        "64"
      ],
      "3MA": [
        "29",
        "33",
        "30",
        "21",
        "51",
        "41",
        "23"
      ],
      "SST": [
        "64"
      ],
      "2TI": [
        "18",
        "26",
        "17",
        "22"
      ],
      "DEU": [
        "46",
        "37",
        "29",
        "49",
        "33",
        "25",
        "26",
        "20",
        "29",
        "22",
        "32",
        "31",
        "19",
        "29",
        "23",
        "22",
        "20",
        "22",
        "21",
        "20",
        "23",
        "29",
        "26",
        "22",
        "19",
        "19",
        "26",
        "69",
        "28",
        "20",
        "30",
        "52",
        "29",
        "12"
      ],
      "1ES": [
        "55",
        "26",
        "24",
        "63",
        "71",
        "33",
        "15",
        "92",
        "55"
      ],
      "HAB": [
        "17",
        "20",
        "19"
      ],
      "JOB": [
        "22",
        "13",
        "26",
        "21",
        "27",
        "30",
        "21",
        "22",
        "35",
        "22",
        "20",
        "25",
        "28",
        "22",
        "35",
        "22",
        "16",
        "21",
        "29",
        "29",
        "34",
        "30",
        "17",
        "25",
        "6",
        "14",
        "23",
        "28",
        "25",
        "31",
        "40",
        "22",
        "33",
        "37",
        "16",
        "33",
        "24",
        "41",
        "30",
        "32",
        "26",
        "17"
      ],
      "SNG": [
        "17",
        "17",
        "11",
        "16",
        "16",
        "12",
        "14",
        "14"
      ],
      "EXO": [
        "22",
        "25",
        "22",
        "31",
        "23",
        "30",
        "29",
        "28",
        "35",
        "29",
        "10",
        "51",
        "22",
        "31",
        "27",
        "36",
        "16",
        "27",
        "25",
        "26",
        "37",
        "30",
        "33",
        "18",
        "40",
        "37",
        "21",
        "43",
        "46",
        "38",
        "18",
        "35",
        "23",
        "35",
        "35",
        "38",
        "29",
        "31",
        "43",
        "38"
      ],
      "JHN": [
        "51",
        "25",
        "36",
        "54",
        "47",
        "71",
        "53",
        "59",
        "41",
        "42",
        "57",
        "50",
        "38",
        "31",
        "27",
        "33",
        "26",
        "40",
        "42",
        "31",
        "25"
      ],
      "PRO": [
        "33",
        "22",
        "35",
        "27",
        "23",
        "35",
        "27",
        "36",
        "18",
        "32",
        "31",
        "28",
        "25",
        "35",
        "33",
        "33",
        "28",
        "24",
        "29",
        "30",
        "31",
        "29",
        "35",
        "34",
        "28",
        "28",
        "27",
        "28",
        "27",
        "33",
        "31"
      ],
      "ESG": [
        "39",
        "23",
        "22",
        "47",
        "28",
        "14",
        "10",
        "41",
        "32",
